default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: <%= ENV['POSTGRESQL_USERNAME'] || 'postgres' %>
 password: <%= ENV['POSTGRESQL_PASSWORD'] || 'postgres' %>
 host: localhost

development:
 <<: *default
 database: extrator_app_development
 port: 5432

test:
 <<: *default
 encoding: utf8
 host: localhost
 timeout: 5000
 database: extrator_app_test

production:
 <<: *default
 database: extrator_app_production
 username: extrator_app
 password: <%= ENV['POSTGRESQL_PASSWORD'] %>
